name: Build & Release ZMK Firmware

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: Build ZMK Firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download merged artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware

      - name: List downloaded files
        run: ls -lR

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ZMK Firmware Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: "*.uf2"          
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
